---
name: Branchprotection
on:
  push:
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: >
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.UPDATEBRANCHPROTECTIONRULETOKEN }}"
          -H "Content-Type: application/json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/teksystemsind/new-demo/branches/master/protection \
          -d '{"required_status_checks": {"strict": true,"contexts": ["continuous-integration/travis-ci"]},"enforce_admins": true,"required_pull_request_reviews": {"dismissal_restrictions": {"users": ["akingupta"],"teams": ["dev"]},"dismiss_stale_reviews": true,"require_code_owner_reviews": true,"required_approving_review_count": 1,"require_last_push_approval": true,"bypass_pull_request_allowances": {"users": ["akingupta"],"teams": ["dev"]}},"restrictions": {"users": ["akingupta"],"teams": ["dev"]},"required_linear_history": false,"allow_force_pushes": false,"allow_deletions": false,"block_creations": false,"required_conversation_resolution": false,"lock_branch": false,"allow_fork_syncing": false}'
